using System.Text.Json;
using FVN_REGISTER.Application.Interfaces.Auths;
using FVN_REGISTER.Application.Interfaces.Equipment;
using FVN_REGISTER.Application.Interfaces.Excel;
using FVN_REGISTER.Application.Interfaces.Security;
using FVN_REGISTER.Application.Interfaces.Users;
using FVN_REGISTER.Contract.Dtos.Authentication;
using FVN_REGISTER.Contract.Dtos.EquipmentImport;
using FVN_REGISTER.Contract.Utils;
using FVN_REGISTER.Core.Constants;
using FVN_REGISTER.Core.Entities.Equipment;
using FVN_REGISTER.Core.Excel;
using FVN_REGISTER.Core.Repositories;
using FVN_REGISTER.Core.Schema;
using FVN_REGISTER.Infrastructure;
using Microsoft.EntityFrameworkCore;

namespace FVN_REGISTER.Infrastructure.Services.Equipment;

public sealed class EquipmentImportService : IEquipmentImportService
{
    private const string ModuleCode="EQUIPMENT", EntityCode="EQUIPMENT_ASSET";
    private readonly FVNWEBAPPContext _db; private readonly IExcelPlatform _excel; private readonly ICurrentUserService _users;
    private readonly IAuthorizationService _auth; private readonly IUnitOfWork _uow;
    public EquipmentImportService(FVNWEBAPPContext db,IExcelPlatform excel,ICurrentUserService users,IAuthorizationService auth,IAuditService audit,IUnitOfWork uow)
        =>(_db,_excel,_users,_auth,_uow)=(db,excel,users,auth,uow);

    public async Task<List<ExcelSchemaSummaryDto>> GetSchemasAsync(string? departmentCode,CancellationToken ct=default)
    {
        var u=User();var dept=Dept(departmentCode,u.DeptCode);await Scope(u,dept,ct);var result=new List<ExcelSchemaSummaryDto>();
        foreach(var s in await _excel.GetSchemasAsync(ModuleCode,EntityCode,false,ct)){var m=await Meta(s.Id,ct);if(!m.DepartmentCode == dept)continue;var owner=m.CreatedBy==u.UserId||u.IsAdmin;result.Add(new(){Id=s.Id,ModuleCode=s.ModuleCode,EntityCode=s.EntityCode,SchemaCode=s.SchemaKey,SchemaName=s.SchemaName,DepartmentCode=m.DepartmentCode,Version=s.Version,Status=s.Status.ToString(),IsActive=s.Status==ExcelSchemaStatus.Active,FieldCount=m.FieldCount,CreatedByUserId=m.CreatedBy,CreatedAt=s.CreatedAt,UpdatedAt=s.UpdatedAt,SourceFileName=s.SourceFileName,CreatedFromExcel=!string.IsNullOrWhiteSpace(s.SourceFileName),IsOwner=owner,CanEdit=owner&&s.Status==ExcelSchemaStatus.Draft,CanCreateVersion=owner,CanClone=true});}return result;
    }
    public async Task<ExcelSchemaDto?> GetSchemaAsync(int id,CancellationToken ct=default){var u=User();var d=await _excel.GetSchemaDefinitionAsync(id,ct);if(d is null)return null;var m=await Meta(id,ct);await Scope(u,m.DepartmentCode,ct);return Map(id,d,m,u);}
    public async Task<ServiceResult<ExcelSchemaDto>> SaveSchemaAsync(ExcelSchemaUpsertRequest r,CancellationToken ct=default){try{var u=User();var dept=Dept(r.DepartmentCode,u.DeptCode);await Scope(u,dept,ct);if(string.IsNullOrWhiteSpace(r.SchemaName))return ServiceResult<ExcelSchemaDto>.Fail("Tên schema là bắt buộc.");if(r.Id is null or <=0){var s=await _excel.CreateDraftSchemaAsync(new ExcelSchemaCreateRequest(ModuleCode,EntityCode,$"{dept}:{Guid.NewGuid():N}",r.SchemaName.Trim(),0,"Sheet1",0,1,null,Array.Empty<int>(),Array.Empty<ExcelSchemaField>()),null,ct);await OwnerSet(s.Id,u.UserId,ct);return ServiceResult<ExcelSchemaDto>.Ok((await GetSchemaAsync(s.Id,ct))!,"Đã tạo schema bản nháp.");}var m=await Meta(r.Id.Value,ct);if(m.CreatedBy!=u.UserId&&!u.IsAdmin)return ServiceResult<ExcelSchemaDto>.Fail("Bạn không có quyền sửa schema.");if(r.Status.Equals("Active",StringComparison.OrdinalIgnoreCase)){var s=await _excel.ActivateSchemaAsync(r.Id.Value,ct);return ServiceResult<ExcelSchemaDto>.Ok((await GetSchemaAsync(s.Id,ct))!,"Đã kích hoạt schema.");}await _db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.F03ExcelSchemas SET SchemaName={r.SchemaName.Trim()},UpdatedBy={u.UserId.ToString()},UpdatedAt=SYSUTCDATETIME() WHERE Id={r.Id.Value} AND Status=0",ct);return ServiceResult<ExcelSchemaDto>.Ok((await GetSchemaAsync(r.Id.Value,ct))!,"Đã lưu schema.");}catch(Exception e)when(e is UnauthorizedAccessException or ArgumentException or InvalidOperationException or KeyNotFoundException){return ServiceResult<ExcelSchemaDto>.Fail(e.Message);}}
    public async Task<ServiceResult<ExcelSchemaDto>> CloneSchemaAsync(int id,ExcelSchemaCloneRequest r,CancellationToken ct=default){try{var u=User();var d=await _excel.GetSchemaDefinitionAsync(id,ct)??throw new KeyNotFoundException("Không tìm thấy schema.");var m=await Meta(id,ct);await Scope(u,m.DepartmentCode,ct);var s=await _excel.CreateDraftSchemaAsync(new ExcelSchemaCreateRequest(ModuleCode,EntityCode,$"{m.DepartmentCode}:{Guid.NewGuid():N}",string.IsNullOrWhiteSpace(r.SchemaName)?$"{m.SchemaName} - Bản sao":r.SchemaName!,d.SheetIndex,d.SheetName,d.HeaderRowIndex,d.DataStartRowIndex,d.DataEndRowIndex,d.SelectedColumnIndexes,d.Fields,d.Culture),m.SourceFileName,ct);await OwnerSet(s.Id,u.UserId,ct);return ServiceResult<ExcelSchemaDto>.Ok((await GetSchemaAsync(s.Id,ct))!,"Đã nhân bản schema.");}catch(Exception e)when(e is UnauthorizedAccessException or ArgumentException or InvalidOperationException or KeyNotFoundException){return ServiceResult<ExcelSchemaDto>.Fail(e.Message);}}
    public async Task<ServiceResult<ExcelSchemaDto>> CreateVersionAsync(int id,CancellationToken ct=default){try{var u=User();var d=await _excel.GetSchemaDefinitionAsync(id,ct)??throw new KeyNotFoundException("Không tìm thấy schema.");var m=await Meta(id,ct);if(m.CreatedBy!=u.UserId&&!u.IsAdmin)throw new UnauthorizedAccessException("Bạn không có quyền tạo phiên bản.");var v=await _db.Database.SqlQueryRaw<int>("SELECT ISNULL(MAX(VersionNo),0)+1 AS Value FROM dbo.F03ExcelSchemaVersions WHERE SchemaId={0}",id).SingleAsync(ct);await _db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO dbo.F03ExcelSchemaVersions(SchemaId,VersionNo,SheetIndex,SheetName,HeaderRowIndex,DataStartRowIndex,DataEndRowIndex,Status,SourceFileName,SelectedColumnsJson,Culture,CreatedAt) VALUES({id},{v},{d.SheetIndex},{d.SheetName},{d.HeaderRowIndex},{d.DataStartRowIndex},{d.DataEndRowIndex},0,{m.SourceFileName},{JsonSerializer.Serialize(d.SelectedColumnIndexes)},{d.Culture},SYSUTCDATETIME())",ct);var vid=await _db.Database.SqlQueryRaw<int>("SELECT TOP 1 Id AS Value FROM dbo.F03ExcelSchemaVersions WHERE SchemaId={0} ORDER BY Id DESC",id).SingleAsync(ct);foreach(var f in d.Fields)await InsertField(vid,f,ct);await _db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.F03ExcelSchemas SET CurrentVersionId={vid},UpdatedAt=SYSUTCDATETIME() WHERE Id={id}",ct);return ServiceResult<ExcelSchemaDto>.Ok((await GetSchemaAsync(id,ct))!,$"Đã tạo phiên bản v{v}.");}catch(Exception e)when(e is UnauthorizedAccessException or ArgumentException or InvalidOperationException or KeyNotFoundException){return ServiceResult<ExcelSchemaDto>.Fail(e.Message);}}
    public async Task<ServiceResult<ExcelSchemaFieldDto>> SaveSchemaFieldAsync(SaveExcelSchemaFieldRequest r,CancellationToken ct=default){try{var u=User();var m=await Meta(r.SchemaId,ct);if(m.CreatedBy!=u.UserId&&!u.IsAdmin)throw new UnauthorizedAccessException("Bạn không có quyền sửa schema.");var vid=await _db.Database.SqlQueryRaw<int?>("SELECT CurrentVersionId AS Value FROM dbo.F03ExcelSchemas WHERE Id={0} AND Status=0",r.SchemaId).SingleOrDefaultAsync(ct)??throw new InvalidOperationException("Schema phải ở trạng thái Draft.");var f=new ExcelSchemaField(r.FieldKey.Trim(),r.DataType.Trim(),r.IsRequired,r.SourceColumnIndex,r.HeaderName,r.Format,r.ResourceKey,r.TargetProperty,r.DisplayOrder,r.AllowEmpty,r.MaxLength,r.DefaultValue,r.ValidationRule);var old=await _db.Database.SqlQueryRaw<int?>("SELECT TOP 1 Id AS Value FROM dbo.F03ExcelSchemaFields WHERE SchemaVersionId={0} AND FieldKey={1}",vid,f.FieldKey).SingleOrDefaultAsync(ct);if(old.HasValue)await _db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.F03ExcelSchemaFields SET DataType={f.DataType},SourceColumnIndex={f.SourceColumnIndex},HeaderName={f.HeaderName},ResourceKey={f.ResourceKey},TargetProperty={f.TargetProperty},Format={f.Format},ValidationRule={f.ValidationRule},DefaultValue={f.DefaultValue},IsRequired={f.Required},AllowEmpty={f.AllowEmpty},MaxLength={f.MaxLength},DisplayOrder={f.DisplayOrder} WHERE Id={old.Value}",ct);else await InsertField(vid,f,ct);var d=await _excel.GetSchemaDefinitionAsync(r.SchemaId,ct)??throw new InvalidOperationException("Không tải được schema.");return ServiceResult<ExcelSchemaFieldDto>.Ok(Map(d.Fields.First(x=>x.FieldKey.Equals(f.FieldKey,StringComparison.OrdinalIgnoreCase))),"Đã lưu field.");}catch(Exception e)when(e is UnauthorizedAccessException or ArgumentException or InvalidOperationException or KeyNotFoundException){return ServiceResult<ExcelSchemaFieldDto>.Fail(e.Message);}}
    public async Task<ServiceResult<ExcelWorkbookDto>> InspectExcelAsync(string? dept,string file,Stream content,CancellationToken ct=default){try{var u=User();await Scope(u,Dept(dept,u.DeptCode),ct);var x=await _excel.InspectAsync(content,file,ct);return ServiceResult<ExcelWorkbookDto>.Ok(new(){FileName=x.FileName,Sheets=x.Sheets.Select(s=>new ExcelSheetDto{Index=s.Index,Name=s.Name,RowCount=Math.Max(0,s.LastRowIndex-s.FirstRowIndex+1),ColumnCount=Math.Max(0,s.LastColumnIndex-s.FirstColumnIndex+1),HasData=s.LastRowIndex>=s.FirstRowIndex}).ToList()});}catch(Exception e)when(e is UnauthorizedAccessException or ArgumentException or InvalidOperationException){return ServiceResult<ExcelWorkbookDto>.Fail(e.Message);}}
    public Task<ServiceResult<ExcelSchemaFromExcelDto>> PreviewSchemaFromExcelSheetAsync(int d,string f,Stream c,int s,CancellationToken ct=default)=>PreviewRange(d,f,c,new(){SheetIndex=s,HeaderRowIndex=0,DataStartRowIndex=1},ct);
    public Task<ServiceResult<ExcelSchemaDto>> CreateSchemaFromExcelSheetAsync(int d,string f,Stream c,int s,string? n,CancellationToken ct=default)=>CreateRange(d,f,c,new(){SheetIndex=s,HeaderRowIndex=0,DataStartRowIndex=1},n,ct);
    public async Task<ServiceResult<ExcelGridDto>> GetExcelGridAsync(string? dept,string file,Stream content,int sheet,int maxRows=200,CancellationToken ct=default){var u=User();await Scope(u,Dept(dept,u.DeptCode),ct);await using var buffer=new MemoryStream();await content.CopyToAsync(buffer,ct);buffer.Position=0;var x=await _excel.InspectAsync(buffer,file,ct);buffer.Position=0;if(sheet<0||sheet>=x.Sheets.Count)return ServiceResult<ExcelGridDto>.Fail("Sheet Excel không hợp lệ.");var s=x.Sheets[sheet];var h=s.HeaderCandidates.FirstOrDefault()??new ExcelHeaderCandidate(s.FirstRowIndex,Array.Empty<string?>(),0);var fs=h.Values.Select((v,i)=>new ExcelSchemaField($"C{i}","Text",false,i,v)).ToList();var p=await _excel.PreviewAsync(buffer,file,new ExcelSchemaDefinition(ModuleCode,EntityCode,"preview",1,sheet,s.Name,h.RowIndex,h.RowIndex+1,Math.Min(s.LastRowIndex,h.RowIndex+maxRows),fs.Select(z=>z.SourceColumnIndex).ToList(),fs),ct);return ServiceResult<ExcelGridDto>.Ok(new(){FileName=file,SheetIndex=sheet,TotalRowCount=p.Rows.Count,ColumnCount=fs.Count,Rows=p.Rows.Select(r=>new ExcelGridRowDto{RowIndex=r.RowIndex-1,Cells=fs.Select(f=>r.Cells.TryGetValue(f.SourceColumnIndex,out var v)?v:null).ToList()}).ToList()});}
    public Task<ServiceResult<ExcelSchemaFromExcelDto>> PreviewSchemaFromExcelRangeAsync(int d,string f,Stream c,ExcelRangeRequest r,CancellationToken ct=default)=>PreviewRange(d,f,c,r,ct);
    public Task<ServiceResult<ExcelSchemaDto>> CreateSchemaFromExcelRangeAsync(int d,string f,Stream c,ExcelRangeRequest r,string? n,CancellationToken ct=default)=>CreateRange(d,f,c,r,n,ct);
    private async Task<ServiceResult<ExcelSchemaFromExcelDto>> PreviewRange(int d,string f,Stream c,ExcelRangeRequest r,CancellationToken ct){var u=User();await Scope(u,Dept(d,u.DeptCode),ct);var x=await _excel.InspectAsync(c,f,ct);if(r.SheetIndex<0||r.SheetIndex>=x.Sheets.Count)return ServiceResult<ExcelSchemaFromExcelDto>.Fail("Sheet Excel không hợp lệ.");var s=x.Sheets[r.SheetIndex];var h=s.HeaderCandidates.FirstOrDefault(z=>z.RowIndex==r.HeaderRowIndex)??s.HeaderCandidates.FirstOrDefault();if(h is null)return ServiceResult<ExcelSchemaFromExcelDto>.Fail("Không tìm thấy dòng tiêu đề.");var cols=(r.SelectedColumnIndexes??Enumerable.Range(0,h.Values.Count)).Where(i=>i>=0&&i<h.Values.Count).Distinct().ToList();var inf=ExcelSchemaInference.Infer(cols.Select(i=>new ExcelSchemaInference.InputColumn(h.Values[i]??$"Column_{i+1}",Array.Empty<string?>())).ToList());return ServiceResult<ExcelSchemaFromExcelDto>.Ok(new(){FileName=Path.GetFileName(f),SuggestedSchemaName=Path.GetFileNameWithoutExtension(f),ColumnCount=inf.Count,SampleRowCount=Math.Max(0,s.LastRowIndex-(r.DataStartRowIndex??r.HeaderRowIndex+1)+1),Fields=inf.Select((z,i)=>new ExcelSchemaFieldDto{FieldKey=z.FieldKey,FieldLabel=z.FieldLabel,DataType=z.DataType,IsRequired=z.IsRequired,AllowEmpty=!z.IsRequired,SourceColumnIndex=cols[i],HeaderName=z.FieldLabel,MaxLength=z.MaxLength,DisplayOrder=i+1}).ToList()});}
    private async Task<ServiceResult<ExcelSchemaDto>> CreateRange(int d,string f,Stream c,ExcelRangeRequest r,string? n,CancellationToken ct){var p=await PreviewRange(d,f,c,r,ct);if(!p.IsSuccess||p.Data is null)return ServiceResult<ExcelSchemaDto>.Fail(p.Message??"Không thể suy luận schema.");var u=User();var dept=Dept(d,u.DeptCode);var fs=p.Data.Fields.Select(z=>new ExcelSchemaField(z.FieldKey,z.DataType,z.IsRequired,z.SourceColumnIndex,z.HeaderName,null,null,z.TargetProperty,z.DisplayOrder,z.AllowEmpty,z.MaxLength,z.DefaultValue,z.ValidationRule)).ToList();var s=await _excel.CreateDraftSchemaAsync(new ExcelSchemaCreateRequest(ModuleCode,EntityCode,$"{dept}:{Guid.NewGuid():N}",string.IsNullOrWhiteSpace(n)?p.Data.SuggestedSchemaName:n!,r.SheetIndex,$"Sheet{r.SheetIndex+1}",r.HeaderRowIndex,r.DataStartRowIndex??r.HeaderRowIndex+1,r.DataEndRowIndex,r.SelectedColumnIndexes??fs.Select(z=>z.SourceColumnIndex).ToList(),fs),Path.GetFileName(f),ct);await OwnerSet(s.Id,u.UserId,ct);return ServiceResult<ExcelSchemaDto>.Ok((await GetSchemaAsync(s.Id,ct))!,"Đã tạo schema từ Excel.");}
    public async Task<ExcelSchemaFromExcelDto> PreviewSchemaFromExcelAsync(string? departmentCode, string fileName, Stream content, CancellationToken ct = default)
    {
        var result = await PreviewSchemaFromExcelSheetAsync(departmentCode, fileName, content, 0, ct);
        if (!result.IsSuccess || result.Data is null)
            throw new InvalidOperationException(result.Message ?? "Không thể suy luận schema từ Excel.");
        return result.Data;
    }

    public async Task<ExcelSchemaDto> CreateSchemaFromExcelAsync(string? departmentCode, string fileName, Stream content, string? schemaName, CancellationToken ct = default)
    {
        var result = await CreateSchemaFromExcelSheetAsync(departmentCode, fileName, content, 0, schemaName, ct);
        if (!result.IsSuccess || result.Data is null)
            throw new InvalidOperationException(result.Message ?? "Không thể tạo schema từ Excel.");
        return result.Data;
    }

    public async Task<ServiceResult<ExcelImportBatchDto>> StageExcelSheetAsync(string? dept,int? schemaId,string file,Stream content,int sheetIndex,bool assignToEmployee=false,CancellationToken ct=default){var u=User();dept=Dept(dept,u.DeptCode);await Scope(u,dept,ct);var sid=schemaId??(await _excel.GetSchemasAsync(ModuleCode,EntityCode,false,ct)).FirstOrDefault(z=>z.Status==ExcelSchemaStatus.Active)?.Id??0;if(sid==0)return ServiceResult<ExcelImportBatchDto>.Fail("Chưa có schema Active.");var d=await _excel.GetSchemaDefinitionAsync(sid,ct)??throw new KeyNotFoundException("Không tìm thấy schema.");var r=await _excel.ImportAsync(content,file,d,ct);await _db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO dbo.F03ExcelImportBatches(SchemaId,SchemaVersionId,ModuleCode,EntityCode,FileName,Status,TotalRows,ValidRows,InvalidRows,ImportedRows,FailedRows,CreatedBy,CreatedAt) VALUES({sid},(SELECT CurrentVersionId FROM dbo.F03ExcelSchemas WHERE Id={sid}),{ModuleCode},{EntityCode},{file},40,{r.TotalRows},{r.ValidRows},{r.InvalidRows},0,0,{u.UserId.ToString()},SYSUTCDATETIME())",ct);var bid=await _db.Database.SqlQueryRaw<long>("SELECT TOP 1 Id AS Value FROM dbo.F03ExcelImportBatches WHERE SchemaId={0} AND FileName={1} ORDER BY Id DESC",sid,file).SingleAsync(ct);foreach(var row in r.Rows){var n=d.Fields.ToDictionary(z=>z.FieldKey,z=>row.Cells.TryGetValue(z.SourceColumnIndex,out var v)?v:null);var er=r.Errors.Where(e=>e.RowNumber==row.RowIndex).ToList();await _db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO dbo.F03ExcelImportRows(BatchId,RowNumber,Status,RawDataJson,NormalizedDataJson,ErrorCount) VALUES({bid},{row.RowIndex},{(er.Count>0?20:30)},{JsonSerializer.Serialize(row.Cells)},{JsonSerializer.Serialize(n)},{er.Count})",ct);foreach(var e in er)await _db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO dbo.F03ExcelImportErrors(BatchId,RowNumber,ColumnIndex,FieldKey,ErrorCode,Severity,ErrorMessage,RawValue,CreatedAt) VALUES({bid},{e.RowNumber},{e.ColumnIndex},{e.FieldKey},{e.Code},{(int)e.Severity},{e.Message},{e.RawValue},SYSUTCDATETIME())",ct);}return ServiceResult<ExcelImportBatchDto>.Ok((await GetBatchAsync(bid,ct))!,"Đã staging file Excel.");}
    public async Task<ExcelImportBatchDto?> GetBatchAsync(long id,CancellationToken ct=default){var u=User();var b=await _db.Database.SqlQueryRaw<Batch>("SELECT Id,SchemaId,ModuleCode,EntityCode,FileName,Status,TotalRows,ValidRows,InvalidRows,ImportedRows FROM dbo.F03ExcelImportBatches WHERE Id={0}",id).SingleOrDefaultAsync(ct);if(b is null)return null;var m=await Meta(b.SchemaId,ct);await Scope(u,m.DepartmentCode,ct);return new(){Id=b.Id,SchemaId=b.SchemaId,ModuleCode=b.ModuleCode,EntityCode=b.EntityCode,FileName=b.FileName,Status=((ExcelImportBatchStatus)b.Status).ToString(),TotalRows=b.TotalRows,ValidRows=b.ValidRows,InvalidRows=b.InvalidRows,ImportedRows=b.ImportedRows};}
    public async Task<ExcelImportCommitResultDto> CommitAsync(long id,CancellationToken ct=default){var u=User();var b=await GetBatchAsync(id,ct)??throw new KeyNotFoundException("Không tìm thấy import batch.");var m=await Meta(b.SchemaId,ct);var rows=await _db.Database.SqlQueryRaw<Row>("SELECT Id,NormalizedDataJson AS Data FROM dbo.F03ExcelImportRows WHERE BatchId={0} AND Status=30",id).ToListAsync(ct);var ok=0;foreach(var row in rows){var d=JsonSerializer.Deserialize<Dictionary<string,string?>>(row.Data??"{}")??new();if(!d.TryGetValue("EquipmentCode",out var code)||!d.TryGetValue("EquipmentName",out var name)||string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(name)||await _db.EquipmentAssets.AnyAsync(x=>x.EquipmentCode==code,ct))continue;await _uow.Repository<F03EquipmentAsset>().AddAsync(new F03EquipmentAsset{EquipmentCode=code.Trim(),EquipmentName=name.Trim(),DeptCode=m.DepartmentCode,PurchaseDate=DateTime.Today,ExpectedDepreciationDate=DateTime.Today.AddYears(5),QrToken=Guid.NewGuid().ToString("N"),IsQrActive=true,CustomDataJson=JsonSerializer.Serialize(d),CreatedBy=u.UserId},ct);await _db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.F03ExcelImportRows SET Status=100 WHERE Id={row.Id}",ct);ok++;}await _uow.SaveChangesAsync(ct);await _db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.F03ExcelImportBatches SET Status=100,ImportedRows={ok},CompletedAt=SYSUTCDATETIME() WHERE Id={id}",ct);return new(){BatchId=id,ImportedRows=ok,SkippedRows=rows.Count-ok};}
    public async Task<ServiceResult<bool>> DeleteDraftSchemaAsync(int id,CancellationToken ct=default){try{var u=User();var m=await Meta(id,ct);if(m.CreatedBy!=u.UserId&&!u.IsAdmin)throw new UnauthorizedAccessException("Bạn không có quyền xóa schema.");await _excel.DeleteDraftSchemaAsync(id,ct);return ServiceResult<bool>.Ok(true,"Đã xóa schema.");}catch(Exception e)when(e is UnauthorizedAccessException or InvalidOperationException or KeyNotFoundException){return ServiceResult<bool>.Fail(e.Message);}}
    private async Task InsertField(int v,ExcelSchemaField f,CancellationToken ct)=>await _db.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO dbo.F03ExcelSchemaFields(SchemaVersionId,FieldKey,DataType,SourceColumnIndex,HeaderName,ResourceKey,TargetProperty,Format,ValidationRule,DefaultValue,IsRequired,AllowEmpty,MaxLength,DisplayOrder) VALUES({v},{f.FieldKey},{f.DataType},{f.SourceColumnIndex},{f.HeaderName},{f.ResourceKey},{f.TargetProperty},{f.Format},{f.ValidationRule},{f.DefaultValue},{f.Required},{f.AllowEmpty},{f.MaxLength},{f.DisplayOrder})",ct);
    private async Task OwnerSet(int id,int user,CancellationToken ct)=>await _db.Database.ExecuteSqlInterpolatedAsync($"UPDATE dbo.F03ExcelSchemas SET CreatedBy={user.ToString()},UpdatedBy={user.ToString()} WHERE Id={id}",ct);
    private async Task<(string DepartmentCode,int CreatedBy,string SchemaName,int FieldCount,string? SourceFileName,int Status)> Meta(int id,CancellationToken ct){var r=await _db.Database.SqlQueryRaw<MetaRow>("SELECT s.SchemaCode Code,s.SchemaName Name,ISNULL(TRY_CONVERT(int,s.CreatedBy),0) ById,(SELECT COUNT(*) FROM dbo.F03ExcelSchemaFields f WHERE f.SchemaVersionId=s.CurrentVersionId) Fields,v.SourceFileName File,s.Status Status FROM dbo.F03ExcelSchemas s LEFT JOIN dbo.F03ExcelSchemaVersions v ON v.Id=s.CurrentVersionId WHERE s.Id={0}",id).SingleOrDefaultAsync(ct)??throw new KeyNotFoundException("Không tìm thấy schema.");var p=r.Code.IndexOf(':');if(p<=0||string.IsNullOrWhiteSpace(r.Code[..p]))throw new InvalidOperationException("Schema không chứa mã phòng ban hợp lệ.");return(r.Code[..p],r.ById,r.Name,r.Fields,r.File,r.Status);}
    private async Task Scope(UserIdentityDto u,string? dept,CancellationToken ct){if(!u.IsAdmin&&u.DeptCode != dept&&!await _auth.HasAsync(u,SecurityFunctionCodes.EquipmentManage,ct))throw new UnauthorizedAccessException("Bạn không có quyền với bộ phận này.");}
    private async Task<string> Owner(int id,CancellationToken ct)=>id<=0?"":await _db.Database.SqlQueryRaw<string>("SELECT TOP 1 FullName Value FROM dbo.F03User WHERE Id={0}",id).FirstOrDefaultAsync(ct)??id.ToString();
    private UserIdentityDto User()=>_users.GetCurrentUser()??throw new UnauthorizedAccessException("Chưa đăng nhập.");
    private static int Dept(int? x, string? fallback) => x ?? fallback ?? throw new ArgumentException("DeptCode là bắt buộc.");
    private static ExcelSchemaDto Map(int id,ExcelSchemaDefinition d,(int DepartmentCode,int CreatedBy,string SchemaName,int FieldCount,string? SourceFileName,int Status)m,UserIdentityDto u)=>new(){Id=id,ModuleCode=d.ModuleCode,EntityCode=d.EntityCode,SchemaCode=d.SchemaKey,SchemaName=m.SchemaName,Version=d.Version,Status=((ExcelSchemaStatus)m.Status).ToString(),IsActive=m.Status==(int)ExcelSchemaStatus.Active,DepartmentCode=m.DepartmentCode,CreatedByUserId=m.CreatedBy,SourceFileName=m.SourceFileName,CreatedFromExcel=!string.IsNullOrWhiteSpace(m.SourceFileName),IsOwner=m.CreatedBy==u.UserId||u.IsAdmin,CanEdit=m.CreatedBy==u.UserId||u.IsAdmin,CanCreateVersion=m.CreatedBy==u.UserId||u.IsAdmin,CanClone=true,SheetIndex=d.SheetIndex,SheetName=d.SheetName,HeaderRowIndex=d.HeaderRowIndex,DataStartRowIndex=d.DataStartRowIndex,DataEndRowIndex=d.DataEndRowIndex,Fields=d.Fields.Select(Map).ToList()};
    private static ExcelSchemaFieldDto Map(ExcelSchemaField f)=>new(){FieldKey=f.FieldKey,FieldLabel=f.HeaderName??f.FieldKey,DataType=f.DataType,IsRequired=f.Required,AllowEmpty=f.AllowEmpty,SourceColumnIndex=f.SourceColumnIndex,HeaderName=f.HeaderName,ResourceKey=f.ResourceKey,TargetProperty=f.TargetProperty,Format=f.Format,ValidationRule=f.ValidationRule,DefaultValue=f.DefaultValue,MaxLength=f.MaxLength,DisplayOrder=f.DisplayOrder};
    private sealed record MetaRow(string Code,string Name,int ById,int Fields,string? File,int Status);private sealed record Batch(long Id,int SchemaId,string ModuleCode,string EntityCode,string FileName,int Status,int TotalRows,int ValidRows,int InvalidRows,int ImportedRows);private sealed record Row(long Id,string? Data);
}