namespace FVN_REGISTER.Shared.Services.Language;

internal static class LanguageCatalogUiCommon
{
    private static readonly IReadOnlyDictionary<string, string> Vi = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["common.save"] = "Lưu", ["common.cancel"] = "Hủy", ["common.delete"] = "Xóa", ["common.edit"] = "Sửa", ["common.add"] = "Thêm", ["common.refresh"] = "Làm mới", ["common.search"] = "Tìm kiếm", ["common.close"] = "Đóng", ["common.confirm"] = "Xác nhận", ["common.yes"] = "Có", ["common.no"] = "Không", ["common.loading"] = "Đang tải...", ["common.noData"] = "Không có dữ liệu", ["common.error"] = "Lỗi", ["common.success"] = "Thành công", ["common.warning"] = "Cảnh báo", ["common.info"] = "Thông tin", ["common.all"] = "Tất cả", ["common.status"] = "Trạng thái", ["common.action"] = "Hành động", ["common.detail"] = "Chi tiết", ["common.createdAt"] = "Ngày tạo", ["common.createdBy"] = "Người tạo", ["common.modifiedAt"] = "Ngày sửa", ["common.modifiedBy"] = "Người sửa", ["common.submit"] = "Gửi", ["common.approve"] = "Duyệt", ["common.reject"] = "Từ chối", ["common.export"] = "Xuất", ["common.import"] = "Nhập", ["common.exportExcel"] = "Xuất Excel", ["common.importExcel"] = "Nhập Excel", ["common.downloadTemplate"] = "Tải file mẫu", ["common.back"] = "Quay lại", ["common.continue"] = "Tiếp tục", ["common.yesDelete"] = "Có, xóa", ["common.noCancel"] = "Không, giữ lại", ["common.selectAll"] = "Chọn tất cả", ["common.deselectAll"] = "Bỏ chọn tất cả", ["common.filter"] = "Bộ lọc", ["common.resetFilter"] = "Đặt lại bộ lọc", ["common.pageSize"] = "Số dòng", ["common.total"] = "Tổng số", ["common.required"] = "Bắt buộc", ["common.notRequired"] = "Không bắt buộc", ["common.enabled"] = "Đang hoạt động", ["common.disabled"] = "Đã tắt", ["common.active"] = "Hoạt động", ["common.inactive"] = "Không hoạt động", ["common.note"] = "Ghi chú", ["common.reason"] = "Lý do", ["common.comment"] = "Ý kiến", ["common.description"] = "Mô tả", ["common.email"] = "Email", ["common.phone"] = "Điện thoại", ["common.employeeCode"] = "Mã nhân viên", ["common.employeeName"] = "Họ tên", ["common.account"] = "Tài khoản", ["common.password"] = "Mật khẩu", ["common.role"] = "Vai trò", ["common.departmentCode"] = "Mã phòng ban", ["common.departmentName"] = "Tên phòng ban", ["common.positionCode"] = "Mã chức vụ", ["common.positionName"] = "Tên chức vụ", ["common.confirmDelete"] = "Bạn có chắc chắn muốn xóa?", ["common.confirmCancel"] = "Bạn có chắc chắn muốn hủy?", ["common.operationSucceeded"] = "Thao tác thành công.", ["common.operationFailed"] = "Thao tác thất bại.", ["common.pleaseSelect"] = "Vui lòng chọn.", ["common.pleaseEnter"] = "Vui lòng nhập.", ["common.pleaseWait"] = "Vui lòng chờ..."
    };

    private static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["common.save"] = "保存", ["common.cancel"] = "キャンセル", ["common.delete"] = "削除", ["common.edit"] = "編集", ["common.add"] = "追加", ["common.refresh"] = "更新", ["common.search"] = "検索", ["common.close"] = "閉じる", ["common.confirm"] = "確認", ["common.yes"] = "はい", ["common.no"] = "いいえ", ["common.loading"] = "読み込み中...", ["common.noData"] = "データがありません", ["common.error"] = "エラー", ["common.success"] = "成功", ["common.warning"] = "警告", ["common.info"] = "情報", ["common.all"] = "すべて", ["common.status"] = "ステータス", ["common.action"] = "操作", ["common.detail"] = "詳細", ["common.createdAt"] = "作成日時", ["common.createdBy"] = "作成者", ["common.modifiedAt"] = "更新日時", ["common.modifiedBy"] = "更新者", ["common.submit"] = "送信", ["common.approve"] = "承認", ["common.reject"] = "却下", ["common.export"] = "出力", ["common.import"] = "取込", ["common.exportExcel"] = "Excel出力", ["common.importExcel"] = "Excel取込", ["common.downloadTemplate"] = "テンプレートをダウンロード", ["common.back"] = "戻る", ["common.continue"] = "続行", ["common.yesDelete"] = "はい、削除", ["common.noCancel"] = "いいえ、残す", ["common.selectAll"] = "すべて選択", ["common.deselectAll"] = "すべて解除", ["common.filter"] = "フィルター", ["common.resetFilter"] = "フィルターをリセット", ["common.pageSize"] = "表示件数", ["common.total"] = "合計", ["common.required"] = "必須", ["common.notRequired"] = "任意", ["common.enabled"] = "有効", ["common.disabled"] = "無効", ["common.active"] = "有効", ["common.inactive"] = "無効", ["common.note"] = "備考", ["common.reason"] = "理由", ["common.comment"] = "コメント", ["common.description"] = "説明", ["common.email"] = "メール", ["common.phone"] = "電話番号", ["common.employeeCode"] = "社員コード", ["common.employeeName"] = "氏名", ["common.account"] = "アカウント", ["common.password"] = "パスワード", ["common.role"] = "ロール", ["common.departmentCode"] = "部署コード", ["common.departmentName"] = "部署名", ["common.positionCode"] = "役職コード", ["common.positionName"] = "役職名", ["common.confirmDelete"] = "削除してもよろしいですか？", ["common.confirmCancel"] = "キャンセルしてもよろしいですか？", ["common.operationSucceeded"] = "処理が成功しました。", ["common.operationFailed"] = "処理に失敗しました。", ["common.pleaseSelect"] = "選択してください。", ["common.pleaseEnter"] = "入力してください。", ["common.pleaseWait"] = "お待ちください..."
    };

    public static bool TryGet(LanguageCode language, string key, out string value) =>
        (language == LanguageCode.Ja ? Ja : Vi).TryGetValue(key, out value!);
}
