namespace FVN_REGISTER.Shared.Services.Language;

internal static class LanguageCatalogModules
{
    private static readonly IReadOnlyDictionary<string, string> Vi = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["dashboard.loading"] = "Đang nạp thông số hệ thống FCC...", ["dashboard.pending"] = "Đơn đang chờ tôi xử lý", ["dashboard.pendingCount"] = "{0} đơn gần nhất", ["dashboard.viewAll"] = "Xem tất cả", ["dashboard.level"] = "Cấp {0}",
        ["dashboard.leave"] = "Phép của tôi", ["dashboard.history"] = "Lịch sử", ["dashboard.entitled"] = "Được hưởng", ["dashboard.used"] = "Đã nghỉ", ["dashboard.remaining"] = "Còn lại", ["dashboard.days"] = "ngày", ["dashboard.nextLeave"] = "Sắp nghỉ", ["dashboard.upcomingDays"] = "Tổng các đợt nghỉ sắp tới: {0} ngày", ["dashboard.noUpcomingLeave"] = "Chưa có ngày nghỉ đã duyệt sắp tới.",
        ["dashboard.ot"] = "OT của tôi", ["dashboard.otWeek"] = "OT tuần", ["dashboard.otMonth"] = "OT tháng", ["dashboard.otYear"] = "OT năm", ["dashboard.otLimitWarning"] = "Có giới hạn OT đang gần chạm. Tuần: {0}h, tháng: {1}h, năm: {2}h.",
        ["dashboard.deptSituation"] = "Tình hình phòng ban — {0}", ["dashboard.managerOnly"] = "Chỉ hiển thị khi tài khoản có quyền quản lý.", ["dashboard.staff"] = "Nhân sự", ["dashboard.absent"] = "Đang vắng", ["dashboard.pending"] = "Chờ duyệt", ["dashboard.absenceRate"] = "Tỷ lệ vắng", ["dashboard.leaveStatistics"] = "Thống kê nghỉ phép phòng ban", ["dashboard.department"] = "Phòng ban", ["dashboard.present"] = "Đang có mặt", ["dashboard.leaveRequests"] = "Đơn nghỉ", ["dashboard.leaveRate"] = "Tỷ lệ nghỉ", ["dashboard.leaveType"] = "Nghỉ phép", ["dashboard.tripType"] = "Công tác",
        ["calendar.title"] = "Lịch làm việc của tôi", ["calendar.managerTitle"] = "Lịch làm việc theo phạm vi quản lý", ["calendar.description"] = "Một ô ngày hợp nhất lịch công ty, ca, chấm công, đăng ký và các vấn đề cần xử lý.", ["calendar.scope"] = "Phạm vi lịch", ["calendar.home"] = "Trang chủ", ["calendar.actionRequired"] = "Cần xử lý trong tháng", ["calendar.handle"] = "Xử lý", ["calendar.dayTitle"] = "Lịch ngày {0}", ["calendar.feedbackTitle"] = "Phản hồi ngày công", ["calendar.cancelOtUnknown"] = "Không xác định được đơn OT cần hủy.", ["calendar.cancelOtReasonRequired"] = "Vui lòng nhập lý do hủy OT.", ["calendar.otCancelled"] = "Đã hủy OT.", ["calendar.otCancelFailed"] = "Không thể hủy OT.", ["calendar.feedbackSelfOnly"] = "Chức năng phản hồi ngày công chỉ gửi cho chính nhân viên đang đăng nhập.", ["calendar.feedbackCreateFailed"] = "Không tạo được hồ sơ phản hồi ngày công.", ["calendar.employeeUnknown"] = "Không xác định được nhân viên của lịch đang mở.", ["calendar.attendanceLoadFailed"] = "Không tải được dữ liệu chấm công của ngày cần phản hồi.", ["calendar.issueNotFound"] = "Không tìm thấy nội dung chênh lệch cần phản hồi. Vui lòng tải lại lịch.", ["calendar.refreshNeeded"] = "Vui lòng tải lại lịch.",
        ["leave.title"] = "Đăng ký nghỉ phép", ["leave.register"] = "Đăng ký nghỉ", ["leave.sharedCalendar"] = "Lịch làm việc chung", ["leave.sharedCalendarDescription"] = "Lịch tổng hợp chấm công, nghỉ phép, OT và công tác được quản lý tập trung tại một nơi.", ["leave.openCalendar"] = "Mở lịch chung", ["leave.loadFailed"] = "Không thể tải dữ liệu. Vui lòng thử lại."
    };

    private static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["dashboard.loading"] = "FCCシステム情報を読み込んでいます...", ["dashboard.pending"] = "処理待ちの申請", ["dashboard.pendingCount"] = "直近{0}件", ["dashboard.viewAll"] = "すべて表示", ["dashboard.level"] = "レベル {0}",
        ["dashboard.leave"] = "自分の休暇", ["dashboard.history"] = "履歴", ["dashboard.entitled"] = "付与日数", ["dashboard.used"] = "取得済み", ["dashboard.remaining"] = "残り", ["dashboard.days"] = "日", ["dashboard.nextLeave"] = "次の休暇", ["dashboard.upcomingDays"] = "今後の休暇合計: {0}日", ["dashboard.noUpcomingLeave"] = "今後の承認済み休暇はありません。",
        ["dashboard.ot"] = "自分の残業", ["dashboard.otWeek"] = "週残業", ["dashboard.otMonth"] = "月残業", ["dashboard.otYear"] = "年残業", ["dashboard.otLimitWarning"] = "残業上限に近づいています。週: {0}h、月: {1}h、年: {2}h。",
        ["dashboard.deptSituation"] = "部門状況 — {0}", ["dashboard.managerOnly"] = "管理権限を持つアカウントにのみ表示されます。", ["dashboard.staff"] = "社員数", ["dashboard.absent"] = "不在", ["dashboard.pending"] = "承認待ち", ["dashboard.absenceRate"] = "不在率", ["dashboard.leaveStatistics"] = "部門休暇統計", ["dashboard.department"] = "部門", ["dashboard.present"] = "出勤", ["dashboard.leaveRequests"] = "休暇申請", ["dashboard.leaveRate"] = "休暇率", ["dashboard.leaveType"] = "休暇", ["dashboard.tripType"] = "出張",
        ["calendar.title"] = "勤務カレンダー", ["calendar.managerTitle"] = "管理範囲の勤務カレンダー", ["calendar.description"] = "会社カレンダー、勤務シフト、勤怠、申請、対応事項を日単位でまとめて表示します。", ["calendar.scope"] = "カレンダー範囲", ["calendar.home"] = "ホーム", ["calendar.actionRequired"] = "今月の対応事項", ["calendar.handle"] = "処理", ["calendar.dayTitle"] = "{0}の勤務カレンダー", ["calendar.feedbackTitle"] = "勤務実績フィードバック", ["calendar.cancelOtUnknown"] = "キャンセルする残業申請を特定できません。", ["calendar.cancelOtReasonRequired"] = "残業キャンセル理由を入力してください。", ["calendar.otCancelled"] = "残業申請をキャンセルしました。", ["calendar.otCancelFailed"] = "残業申請をキャンセルできませんでした。", ["calendar.feedbackSelfOnly"] = "勤務実績フィードバックはログイン中の本人のみ送信できます。", ["calendar.feedbackCreateFailed"] = "勤務実績フィードバックを作成できませんでした。", ["calendar.employeeUnknown"] = "表示中のカレンダーの社員を特定できません。", ["calendar.attendanceLoadFailed"] = "フィードバック対象日の勤怠データを読み込めませんでした。", ["calendar.issueNotFound"] = "対応する不一致を見つけられません。カレンダーを再読み込みしてください。", ["calendar.refreshNeeded"] = "カレンダーを再読み込みしてください。",
        ["leave.title"] = "休暇申請", ["leave.register"] = "休暇を申請", ["leave.sharedCalendar"] = "共通勤務カレンダー", ["leave.sharedCalendarDescription"] = "勤怠、休暇、残業、出張を一つのカレンダーで集中管理します。", ["leave.openCalendar"] = "共通カレンダーを開く", ["leave.loadFailed"] = "データを読み込めませんでした。もう一度お試しください。"
    };

    public static bool TryGet(LanguageCode language, string key, out string value) =>
        (language == LanguageCode.Ja ? Ja : Vi).TryGetValue(key, out value!);
}
