namespace FVN_REGISTER.Shared.Services.Language;

internal static class LanguageCatalogRemaining
{
    private static readonly IReadOnlyDictionary<string, string> Vi = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["ot.title"] = "Làm thêm giờ (OT)", ["ot.create"] = "Đăng ký OT", ["ot.list"] = "Danh sách đơn OT", ["ot.history"] = "Lịch sử OT", ["ot.employee"] = "Nhân viên", ["ot.department"] = "Phòng ban", ["ot.date"] = "Ngày", ["ot.from"] = "Từ giờ", ["ot.to"] = "Đến giờ", ["ot.hours"] = "Số giờ", ["ot.reason"] = "Lý do OT", ["ot.status"] = "Trạng thái", ["ot.limit"] = "Hạn mức OT", ["ot.week"] = "Tuần", ["ot.month"] = "Tháng", ["ot.year"] = "Năm", ["ot.approval"] = "Phê duyệt OT", ["ot.reapprove"] = "Phê duyệt lại", ["ot.cancel"] = "Hủy OT", ["ot.cancelReason"] = "Lý do hủy OT", ["ot.actual"] = "Giờ OT thực tế", ["ot.registered"] = "Giờ OT đăng ký", ["ot.mismatch"] = "Lệch giờ OT", ["ot.noActual"] = "Có đăng ký nhưng chưa có giờ thực tế", ["ot.noApproval"] = "Có giờ thực tế nhưng chưa có OT được duyệt", ["ot.reapprovalReason"] = "Lý do phê duyệt lại",
        ["trip.title"] = "Công tác", ["trip.create"] = "Đăng ký công tác", ["trip.list"] = "Danh sách đơn công tác", ["trip.history"] = "Lịch sử công tác", ["trip.destination"] = "Địa điểm công tác", ["trip.fromDate"] = "Từ ngày", ["trip.toDate"] = "Đến ngày", ["trip.purpose"] = "Mục đích", ["trip.employee"] = "Nhân viên", ["trip.status"] = "Trạng thái", ["trip.actual"] = "Thực tế công tác", ["trip.registered"] = "Đã đăng ký", ["trip.reRegister"] = "Đăng ký lại",
        ["equipment.title"] = "Thiết bị", ["equipment.register"] = "Sổ quản lý thiết bị", ["equipment.create"] = "Thêm thiết bị", ["equipment.edit"] = "Sửa thiết bị", ["equipment.import"] = "Import Excel thiết bị", ["equipment.handover"] = "Bàn giao thiết bị", ["equipment.code"] = "Mã thiết bị", ["equipment.name"] = "Tên thiết bị", ["equipment.serial"] = "Serial", ["equipment.department"] = "Phòng ban", ["equipment.employee"] = "Người phụ trách", ["equipment.location"] = "Vị trí", ["equipment.status"] = "Trạng thái", ["equipment.importBatch"] = "Lô import", ["equipment.importResult"] = "Kết quả import", ["equipment.qr"] = "Mã QR", ["equipment.repair"] = "Sửa chữa", ["equipment.history"] = "Lịch sử thiết bị",
        ["approval.title"] = "Phê duyệt", ["approval.pending"] = "Danh sách chờ duyệt", ["approval.request"] = "Yêu cầu", ["approval.requester"] = "Người yêu cầu", ["approval.module"] = "Nghiệp vụ", ["approval.level"] = "Cấp duyệt", ["approval.decision"] = "Quyết định", ["approval.comment"] = "Ý kiến", ["approval.approve"] = "Duyệt", ["approval.reject"] = "Từ chối", ["approval.return"] = "Trả lại", ["approval.reasonRequired"] = "Vui lòng nhập lý do.", ["approval.approved"] = "Đã duyệt", ["approval.rejected"] = "Đã từ chối", ["approval.waiting"] = "Đang chờ duyệt",
        ["security.title"] = "Security Center", ["security.users"] = "Tài khoản & quyền hiệu lực", ["security.roles"] = "Role → Function / Action", ["security.policies"] = "Approval Policy", ["security.twoFactor"] = "2FA theo tài khoản", ["security.functions"] = "Chức năng", ["security.actions"] = "Thao tác", ["security.scope"] = "Phạm vi", ["security.role"] = "Role", ["security.permission"] = "Quyền", ["security.effective"] = "Quyền hiệu lực", ["security.grant"] = "Cấp quyền", ["security.revoke"] = "Thu hồi quyền", ["security.twoFactorRequired"] = "Bắt buộc 2FA", ["security.qr"] = "Mã QR Authenticator", ["security.secret"] = "Khóa bí mật", ["security.sessions"] = "Thiết bị & phiên đăng nhập",
        ["hrm.title"] = "HRM", ["hrm.sync"] = "Đồng bộ HRM", ["hrm.calculate"] = "Tính giờ theo HRM", ["hrm.attendance"] = "Chấm công", ["hrm.conflict"] = "Conflict HRM", ["hrm.roleRules"] = "Role HRM → User", ["hrm.department"] = "Phòng ban", ["hrm.position"] = "Chức vụ", ["hrm.employee"] = "Nhân viên", ["hrm.syncNow"] = "Đồng bộ ngay", ["hrm.calculateNow"] = "Tính giờ ngay", ["hrm.lastRun"] = "Lần chạy gần nhất", ["hrm.result"] = "Kết quả", ["hrm.error"] = "Lỗi đồng bộ",
        ["payroll.title"] = "Tính lương", ["payroll.table"] = "Bảng công tính lương", ["payroll.period"] = "Kỳ tính lương", ["payroll.fromDate"] = "Từ ngày", ["payroll.toDate"] = "Đến ngày", ["payroll.status"] = "Trạng thái", ["payroll.prepare"] = "Chuẩn bị", ["payroll.calculate"] = "Tính toán", ["payroll.lock"] = "Khóa kỳ", ["payroll.export"] = "Xuất bảng công", ["payroll.print"] = "In bảng công", ["payroll.locked"] = "Đã khóa", ["payroll.unlocked"] = "Chưa khóa", ["payroll.employee"] = "Nhân viên", ["payroll.workDays"] = "Ngày công", ["payroll.workHours"] = "Giờ công", ["payroll.otHours"] = "Giờ OT",
        ["report.title"] = "Báo cáo & thống kê", ["report.center"] = "Trung tâm báo cáo", ["report.leave"] = "Báo cáo nghỉ phép", ["report.ot"] = "Báo cáo OT", ["report.trip"] = "Báo cáo công tác", ["report.equipment"] = "Báo cáo thiết bị", ["report.attendance"] = "Báo cáo chấm công", ["report.export"] = "Xuất báo cáo", ["report.fromDate"] = "Từ ngày", ["report.toDate"] = "Đến ngày", ["report.department"] = "Phòng ban",
        ["public.title"] = "Thông tin công khai", ["public.forms"] = "Biểu mẫu đăng ký", ["public.manageForms"] = "Quản lý biểu mẫu đăng ký", ["public.target"] = "Đối tượng nhận", ["public.company"] = "Toàn công ty", ["public.department"] = "Phòng ban", ["public.position"] = "Chức vụ", ["public.employee"] = "Nhân viên", ["public.publish"] = "Công khai", ["public.unpublish"] = "Ngừng công khai", ["public.operator"] = "Người vận hành", ["public.content"] = "Nội dung", ["public.expiry"] = "Ngày hết hạn",
        ["endpoint.title"] = "Endpoint Governance", ["endpoint.inventory"] = "Danh mục Endpoint", ["endpoint.catalog"] = "Danh mục phần mềm / dịch vụ", ["endpoint.credentials"] = "Thông tin xác thực Agent", ["endpoint.device"] = "Thiết bị Endpoint", ["endpoint.software"] = "Phần mềm", ["endpoint.service"] = "Dịch vụ", ["endpoint.policy"] = "Policy", ["endpoint.compliance"] = "Compliance", ["endpoint.findings"] = "Finding", ["endpoint.serial"] = "Serial", ["endpoint.hardwareUuid"] = "Hardware UUID", ["endpoint.rotate"] = "Rotate key", ["endpoint.revoke"] = "Revoke key", ["endpoint.provision"] = "Provision Agent", ["endpoint.linkEquipment"] = "Liên kết Equipment",
        ["access.title"] = "Thay đổi quyền / bàn giao", ["access.create"] = "Lập phiếu", ["access.mine"] = "Phiếu của tôi", ["access.pending"] = "Chờ tôi duyệt", ["access.itQueue"] = "IT xử lý", ["access.oldEmployee"] = "Nhân sự cũ", ["access.newEmployee"] = "Người nhận", ["access.transferResponsible"] = "Bàn giao thiết bị người cũ đang phụ trách", ["access.transferApprover"] = "Bàn giao vai trò approver thiết bị", ["access.functions"] = "Quyền sẽ chuyển", ["access.execute"] = "Thiết lập", ["access.preChange"] = "Thông tin trước bàn giao",
        ["common.previous"] = "Trước", ["common.next"] = "Sau", ["common.select"] = "Chọn", ["common.code"] = "Mã", ["common.name"] = "Tên", ["common.type"] = "Loại", ["common.from"] = "Từ", ["common.to"] = "Đến", ["common.download"] = "Tải xuống", ["common.upload"] = "Tải lên", ["common.apply"] = "Áp dụng", ["common.reset"] = "Đặt lại", ["common.clear"] = "Xóa lọc", ["common.view"] = "Xem", ["common.manage"] = "Quản lý", ["common.requiredField"] = "Trường bắt buộc", ["common.optional"] = "Không bắt buộc"
    };

    private static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["ot.title"] = "残業（OT）", ["ot.create"] = "残業申請", ["ot.list"] = "残業申請一覧", ["ot.history"] = "残業履歴", ["ot.employee"] = "社員", ["ot.department"] = "部署", ["ot.date"] = "日付", ["ot.from"] = "開始時刻", ["ot.to"] = "終了時刻", ["ot.hours"] = "時間数", ["ot.reason"] = "残業理由", ["ot.status"] = "ステータス", ["ot.limit"] = "残業上限", ["ot.week"] = "週", ["ot.month"] = "月", ["ot.year"] = "年", ["ot.approval"] = "残業承認", ["ot.reapprove"] = "再承認", ["ot.cancel"] = "残業キャンセル", ["ot.cancelReason"] = "キャンセル理由", ["ot.actual"] = "実績残業時間", ["ot.registered"] = "申請残業時間", ["ot.mismatch"] = "残業時間不一致", ["ot.noActual"] = "申請済みですが実績時間がありません", ["ot.noApproval"] = "実績時間がありますが承認済み残業がありません", ["ot.reapprovalReason"] = "再承認理由",
        ["trip.title"] = "出張", ["trip.create"] = "出張申請", ["trip.list"] = "出張申請一覧", ["trip.history"] = "出張履歴", ["trip.destination"] = "出張先", ["trip.fromDate"] = "開始日", ["trip.toDate"] = "終了日", ["trip.purpose"] = "目的", ["trip.employee"] = "社員", ["trip.status"] = "ステータス", ["trip.actual"] = "実績出張", ["trip.registered"] = "申請済み", ["trip.reRegister"] = "再申請",
        ["equipment.title"] = "設備", ["equipment.register"] = "設備管理台帳", ["equipment.create"] = "設備追加", ["equipment.edit"] = "設備編集", ["equipment.import"] = "設備Excel取込", ["equipment.handover"] = "設備引継ぎ", ["equipment.code"] = "設備コード", ["equipment.name"] = "設備名", ["equipment.serial"] = "シリアル", ["equipment.department"] = "部署", ["equipment.employee"] = "担当者", ["equipment.location"] = "場所", ["equipment.status"] = "ステータス", ["equipment.importBatch"] = "取込バッチ", ["equipment.importResult"] = "取込結果", ["equipment.qr"] = "QRコード", ["equipment.repair"] = "修理", ["equipment.history"] = "設備履歴",
        ["approval.title"] = "承認", ["approval.pending"] = "承認待ち一覧", ["approval.request"] = "申請", ["approval.requester"] = "申請者", ["approval.module"] = "業務", ["approval.level"] = "承認レベル", ["approval.decision"] = "決定", ["approval.comment"] = "コメント", ["approval.approve"] = "承認", ["approval.reject"] = "却下", ["approval.return"] = "差し戻し", ["approval.reasonRequired"] = "理由を入力してください。", ["approval.approved"] = "承認済み", ["approval.rejected"] = "却下済み", ["approval.waiting"] = "承認待ち",
        ["security.title"] = "セキュリティセンター", ["security.users"] = "アカウントと有効権限", ["security.roles"] = "Role → Function / Action", ["security.policies"] = "承認ポリシー", ["security.twoFactor"] = "アカウント別2FA", ["security.functions"] = "機能", ["security.actions"] = "操作", ["security.scope"] = "範囲", ["security.role"] = "Role", ["security.permission"] = "権限", ["security.effective"] = "有効権限", ["security.grant"] = "権限付与", ["security.revoke"] = "権限取消", ["security.twoFactorRequired"] = "2FA必須", ["security.qr"] = "Authenticator QRコード", ["security.secret"] = "秘密鍵", ["security.sessions"] = "デバイスとログインセッション",
        ["hrm.title"] = "HRM", ["hrm.sync"] = "HRM同期", ["hrm.calculate"] = "HRM勤怠計算", ["hrm.attendance"] = "勤怠", ["hrm.conflict"] = "HRM競合", ["hrm.roleRules"] = "HRMロール → ユーザー", ["hrm.department"] = "部署", ["hrm.position"] = "役職", ["hrm.employee"] = "社員", ["hrm.syncNow"] = "今すぐ同期", ["hrm.calculateNow"] = "今すぐ計算", ["hrm.lastRun"] = "最終実行", ["hrm.result"] = "結果", ["hrm.error"] = "同期エラー",
        ["payroll.title"] = "給与計算", ["payroll.table"] = "給与計算用勤務表", ["payroll.period"] = "給与計算期間", ["payroll.fromDate"] = "開始日", ["payroll.toDate"] = "終了日", ["payroll.status"] = "ステータス", ["payroll.prepare"] = "準備", ["payroll.calculate"] = "計算", ["payroll.lock"] = "期間ロック", ["payroll.export"] = "勤務表出力", ["payroll.print"] = "勤務表印刷", ["payroll.locked"] = "ロック済み", ["payroll.unlocked"] = "未ロック", ["payroll.employee"] = "社員", ["payroll.workDays"] = "勤務日数", ["payroll.workHours"] = "勤務時間", ["payroll.otHours"] = "残業時間",
        ["report.title"] = "レポート・統計", ["report.center"] = "レポートセンター", ["report.leave"] = "休暇レポート", ["report.ot"] = "残業レポート", ["report.trip"] = "出張レポート", ["report.equipment"] = "設備レポート", ["report.attendance"] = "勤怠レポート", ["report.export"] = "レポート出力", ["report.fromDate"] = "開始日", ["report.toDate"] = "終了日", ["report.department"] = "部署",
        ["public.title"] = "公開情報", ["public.forms"] = "申請フォーム", ["public.manageForms"] = "申請フォーム管理", ["public.target"] = "対象", ["public.company"] = "全社", ["public.department"] = "部署", ["public.position"] = "役職", ["public.employee"] = "社員", ["public.publish"] = "公開", ["public.unpublish"] = "公開停止", ["public.operator"] = "運用担当者", ["public.content"] = "内容", ["public.expiry"] = "有効期限",
        ["endpoint.title"] = "Endpoint Governance", ["endpoint.inventory"] = "Endpoint インベントリ", ["endpoint.catalog"] = "ソフトウェア / サービスカタログ", ["endpoint.credentials"] = "Agent 認証情報", ["endpoint.device"] = "Endpoint デバイス", ["endpoint.software"] = "ソフトウェア", ["endpoint.service"] = "サービス", ["endpoint.policy"] = "ポリシー", ["endpoint.compliance"] = "コンプライアンス", ["endpoint.findings"] = "検出結果", ["endpoint.serial"] = "シリアル", ["endpoint.hardwareUuid"] = "Hardware UUID", ["endpoint.rotate"] = "キー更新", ["endpoint.revoke"] = "キー取消", ["endpoint.provision"] = "Agentプロビジョニング", ["endpoint.linkEquipment"] = "Equipment連携",
        ["access.title"] = "権限変更・引継ぎ", ["access.create"] = "申請作成", ["access.mine"] = "自分の申請", ["access.pending"] = "承認待ち", ["access.itQueue"] = "IT処理", ["access.oldEmployee"] = "旧担当者", ["access.newEmployee"] = "引継ぎ先", ["access.transferResponsible"] = "旧担当者が管理する設備を引継ぐ", ["access.transferApprover"] = "設備承認者ロールを引継ぐ", ["access.functions"] = "引継ぐ権限", ["access.execute"] = "設定", ["access.preChange"] = "変更前情報",
        ["common.previous"] = "前へ", ["common.next"] = "次へ", ["common.select"] = "選択", ["common.code"] = "コード", ["common.name"] = "名称", ["common.type"] = "種類", ["common.from"] = "開始", ["common.to"] = "終了", ["common.download"] = "ダウンロード", ["common.upload"] = "アップロード", ["common.apply"] = "適用", ["common.reset"] = "リセット", ["common.clear"] = "クリア", ["common.view"] = "表示", ["common.manage"] = "管理", ["common.requiredField"] = "必須項目", ["common.optional"] = "任意"
    };

    public static bool TryGet(LanguageCode language, string key, out string value) =>
        (language == LanguageCode.Ja ? Ja : Vi).TryGetValue(key, out value!);
}
