[CmdletBinding(DefaultParameterSetName='Build')]
param(
    [Parameter(ParameterSetName='Keys',Mandatory)][switch]$GenerateKeys,
    [Parameter(ParameterSetName='Keys',Mandatory)][string]$KeyDir,
    [Parameter(ParameterSetName='Build',Mandatory)][string]$Version,
    [Parameter(ParameterSetName='Build',Mandatory)][string]$PrivateKeyFile,
    [Parameter(ParameterSetName='Build')][ValidateSet('api','web','both')][string]$Components='both',
    [Parameter(ParameterSetName='Build')][ValidateSet('full','overlay')][string]$Mode='full',
    [Parameter(ParameterSetName='Build')][string]$BaselineVersion,
    [Parameter(ParameterSetName='Build')][string[]]$SqlFiles=@(),
    [Parameter(ParameterSetName='Build')][string]$Notes='',
    [Parameter(ParameterSetName='Build')][string]$OutDir,
    [Parameter(ParameterSetName='Build')][string]$Configuration='Release'
)
$ErrorActionPreference='Stop';Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem
if($PSCmdlet.ParameterSetName-eq'Keys'){New-Item -ItemType Directory -Path $KeyDir -Force|Out-Null;$rsa=New-Object System.Security.Cryptography.RSACryptoServiceProvider 3072;$rsa.PersistKeyInCsp=$false;[IO.File]::WriteAllText((Join-Path $KeyDir 'private.xml'),$rsa.ToXmlString($true));[IO.File]::WriteAllText((Join-Path $KeyDir 'public.xml'),$rsa.ToXmlString($false));Write-Host "Created signing keys in $KeyDir. Keep private.xml secret." -ForegroundColor Yellow;return}
if($Version-notmatch'^[0-9A-Za-z][0-9A-Za-z._-]{0,40}$'){throw 'Invalid Version.'};if($Mode-eq'overlay'-and-not$BaselineVersion){throw '-Mode overlay requires -BaselineVersion.'}
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;if(-not$OutDir){$OutDir=Join-Path $repo 'patches'};New-Item -ItemType Directory -Path $OutDir -Force|Out-Null
$compList=if($Components-eq'both'){@('api','web')}else{@($Components)};$projects=@{api='FVN_REGISTER.API\FVN_REGISTER.API.csproj';web='FVN_REGISTER.Web\FVN_REGISTER.Web.csproj'};$neverShip=@('appsettings.Production.json','appsettings.Development.json','web.config');$stage=Join-Path $OutDir "stage-$Version";if(Test-Path $stage){Remove-Item $stage -Recurse -Force}
foreach($c in $compList){$target=Join-Path $stage $c;& dotnet publish (Join-Path $repo $projects[$c]) -c $Configuration -o $target --nologo -v quiet;if($LASTEXITCODE-ne0){throw "dotnet publish failed for $c"};foreach($n in $neverShip){$p=Join-Path $target $n;if(Test-Path $p){Remove-Item $p -Force}}}
function Get-Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
$entries=[ordered]@{};$delete=@{api=@();web=@()}
foreach($c in $compList){$newRoot=Join-Path $stage $c;$newLen=$newRoot.TrimEnd('\').Length+1;$baseRoot=if($Mode-eq'overlay'){Join-Path $OutDir "stage-$BaselineVersion\$c"}else{$null};if($Mode-eq'overlay'-and-not(Test-Path $baseRoot)){throw "Baseline not found: $baseRoot"};foreach($f in Get-ChildItem -LiteralPath $newRoot -Recurse -File){$rel=$f.FullName.Substring($newLen);if($Mode-eq'overlay'){$b=Join-Path $baseRoot $rel;if((Test-Path $b)-and((Get-Hash $b)-eq(Get-Hash $f.FullName))){continue}};$entries["$c/"+$rel.Replace('\','/')]= $f.FullName};if($Mode-eq'overlay'){$baseLen=$baseRoot.TrimEnd('\').Length+1;foreach($f in Get-ChildItem -LiteralPath $baseRoot -Recurse -File){$rel=$f.FullName.Substring($baseLen);if(-not(Test-Path(Join-Path $newRoot $rel))){$delete[$c]+=$rel}}}}
$sqlNames=@();foreach($s in $SqlFiles){if(-not(Test-Path $s)){throw "SQL file not found: $s"};$name=Split-Path -Leaf $s;if($name-notmatch'^[^/\\]+\.sql$'){throw "Bad SQL file name: $name"};$entries["sql/$name"]=(Resolve-Path $s).Path;$sqlNames+="sql/$name"}
if($entries.Count-eq0-and($delete.api.Count+$delete.web.Count)-eq0){throw 'Nothing to ship.'}
$files=[ordered]@{};foreach($k in $entries.Keys){$files[$k]=Get-Hash $entries[$k]};$manifest=[ordered]@{version=$Version;mode=$Mode;components=@($compList);createdAt=(Get-Date).ToString('o');createdOn=$env:COMPUTERNAME;notes=$Notes;sql=@($sqlNames);delete=[ordered]@{api=@($delete.api);web=@($delete.web)};files=$files};$utf8=New-Object System.Text.UTF8Encoding($false);$manifestBytes=$utf8.GetBytes(($manifest|ConvertTo-Json -Depth 8));$rsa=New-Object System.Security.Cryptography.RSACryptoServiceProvider;$rsa.PersistKeyInCsp=$false;$rsa.FromXmlString([IO.File]::ReadAllText($PrivateKeyFile));if($rsa.PublicOnly){throw 'Private key required.'};$sha=[System.Security.Cryptography.SHA256]::Create();$sig=$rsa.SignHash($sha.ComputeHash($manifestBytes),[System.Security.Cryptography.HashAlgorithmName]::SHA256,[System.Security.Cryptography.RSASignaturePadding]::Pkcs1);$sigBytes=$utf8.GetBytes([Convert]::ToBase64String($sig))
$zipPath=Join-Path $OutDir "patch-$Version.zip";if(Test-Path $zipPath){Remove-Item $zipPath -Force};$fs=[IO.File]::Open($zipPath,[IO.FileMode]::Create);$za=New-Object System.IO.Compression.ZipArchive($fs,[System.IO.Compression.ZipArchiveMode]::Create);try{foreach($k in $entries.Keys){[void][System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($za,$entries[$k],$k,[System.IO.Compression.CompressionLevel]::Optimal)};$e=$za.CreateEntry('manifest.json');$s=$e.Open();$s.Write($manifestBytes,0,$manifestBytes.Length);$s.Dispose();$e=$za.CreateEntry('manifest.sig');$s=$e.Open();$s.Write($sigBytes,0,$sigBytes.Length);$s.Dispose()}finally{$za.Dispose();$fs.Dispose()};Write-Host "Created $zipPath" -ForegroundColor Green
