# Shared helpers for the FVN_REGISTER updater. Windows PowerShell 5.1 / PowerShell 7.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

function Initialize-Updater {
    param([Parameter(Mandatory)][string]$ConfigPath)
    $script:Cfg = Get-Content -LiteralPath $ConfigPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $script:Root = $script:Cfg.root
    $script:InboxDir = Join-Path $script:Root 'patch-inbox'
    $script:StatusDir = Join-Path $script:Root 'patch-status'
    $script:DoneDir = Join-Path $script:Root 'patch-processed'
    $script:RejectDir = Join-Path $script:Root 'patch-rejected'
    $script:WorkRoot = Join-Path $script:Root 'work'
    $script:KeyFile = Join-Path $script:Root 'keys\public.xml'
    $script:LogFile = Join-Path $script:Root 'updater\updater.log'
    $script:St = $null
    foreach ($d in @($script:InboxDir,$script:StatusDir,$script:DoneDir,$script:RejectDir,$script:WorkRoot)) { if (-not (Test-Path -LiteralPath $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null } }
    Import-Module WebAdministration -ErrorAction Stop
}
function Write-UpdLog { param([string]$Message,[string]$Level='INFO'); $line='{0:yyyy-MM-dd HH:mm:ss} [{1}] {2}' -f (Get-Date),$Level,$Message; try{Add-Content -LiteralPath $script:LogFile -Value $line -Encoding UTF8}catch{}; Write-Host $line }
function Get-ComponentNames { @($script:Cfg.components.PSObject.Properties | ForEach-Object { $_.Name }) }
function Get-Component { param([string]$Name); $p=$script:Cfg.components.PSObject.Properties[$Name]; if($null -eq $p){return $null}; $p.Value }
function Save-Json { param($Object,[string]$Path,[int]$Depth=10); $tmp="$Path.tmp"; ($Object|ConvertTo-Json -Depth $Depth)|Set-Content -LiteralPath $tmp -Encoding UTF8; Move-Item -LiteralPath $tmp -Destination $Path -Force }
function Save-Status { Save-Json -Object $script:St -Path (Join-Path $script:StatusDir 'status.json') }
function Start-Status { param([string]$Id,[string]$Version,[string]$Uploader); $script:St=[ordered]@{id=$Id;state='Running';version=$Version;message='';uploadedBy=$Uploader;startedAt=(Get-Date).ToString('o');finishedAt=$null;steps=@()}; Save-Status }
function Add-Step { param([string]$Text); Write-UpdLog $Text; if($null -eq $script:St){return}; $script:St.steps=@($script:St.steps)+@(@{at=(Get-Date).ToString('o');text=$Text}); Save-Status }
function Complete-Status { param([string]$State,[string]$Message); $script:St.state=$State;$script:St.message=$Message;$script:St.finishedAt=(Get-Date).ToString('o');Save-Status;$historyPath=Join-Path $script:StatusDir 'history.json';$items=@();if(Test-Path -LiteralPath $historyPath){try{$items=@(Get-Content -LiteralPath $historyPath -Raw -Encoding UTF8|ConvertFrom-Json)}catch{$items=@()}};$items+=[pscustomobject]@{id=$script:St.id;state=$State;version=$script:St.version;message=$Message;uploadedBy=$script:St.uploadedBy;startedAt=$script:St.startedAt;finishedAt=$script:St.finishedAt};Save-Json -Object @($items|Select-Object -Last 50) -Path $historyPath }
function New-Rejection { param([string]$Message); New-Object System.Security.SecurityException $Message }
function Load-RsaPublicKey { param([string]$Xml); $root=[System.Xml.Linq.XElement]::Parse($Xml); $read={param($name);$v=$root.Descendants()|Where-Object{$_.Name.LocalName -eq $name}|Select-Object -First 1;if($null -eq $v -or [string]::IsNullOrWhiteSpace($v.Value)){throw "RSA key missing $name"};[Convert]::FromBase64String($v.Value)};$rsa=[System.Security.Cryptography.RSA]::Create();$rsa.ImportParameters([System.Security.Cryptography.RSAParameters]@{Modulus=&$read 'Modulus';Exponent=&$read 'Exponent'});$rsa }
function Test-ManifestSignature { param([string]$ManifestPath,[string]$SignaturePath,[string]$PublicKeyXml); $rsa=Load-RsaPublicKey $PublicKeyXml;try{$sig=[Convert]::FromBase64String((Get-Content -LiteralPath $SignaturePath -Raw).Trim());$hash=[System.Security.Cryptography.SHA256]::Create();return $rsa.VerifyHash($hash.ComputeHash([IO.File]::ReadAllBytes($ManifestPath)),$sig,[System.Security.Cryptography.HashAlgorithmName]::SHA256,[System.Security.Cryptography.RSASignaturePadding]::Pkcs1)}finally{$rsa.Dispose()} }
function Expand-ZipSafe { param([string]$Zip,[string]$Dest,[long]$MaxBytes);New-Item -ItemType Directory -Path $Dest -Force|Out-Null;$destFull=[IO.Path]::GetFullPath($Dest).TrimEnd('\')+'\';$za=[IO.Compression.ZipFile]::OpenRead($Zip);try{$total=0L;foreach($e in $za.Entries){$total+=$e.Length};if($total -gt $MaxBytes){throw(New-Rejection "Package expands to $total bytes (limit $MaxBytes).")};foreach($e in $za.Entries){if([string]::IsNullOrEmpty($e.Name)){continue};$target=[IO.Path]::GetFullPath((Join-Path $Dest $e.FullName));if(-not $target.StartsWith($destFull,[StringComparison]::OrdinalIgnoreCase)){throw(New-Rejection "Illegal path in package: $($e.FullName)")};$dir=Split-Path -Parent $target;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};[IO.Compression.ZipFileExtensions]::ExtractToFile($e,$target,$true)}}finally{$za.Dispose()} }
function Test-SafeRelativePath { param([string]$Path);if([string]::IsNullOrWhiteSpace($Path)){return $false};if([IO.Path]::IsPathRooted($Path)){return $false};if($Path -match '(^|[\\/])\.\.([\\/]|$)'){return $false};$true }
function Assert-Manifest { param($Manifest,[string]$WorkDir);if($Manifest.version -notmatch '^[0-9A-Za-z][0-9A-Za-z._-]{0,40}$'){throw(New-Rejection 'Invalid version in manifest.')};if(@('full','overlay') -notcontains $Manifest.mode){throw(New-Rejection 'Manifest mode must be full or overlay.')};$known=Get-ComponentNames;$comps=@($Manifest.components);if($comps.Count -eq 0){throw(New-Rejection 'Manifest lists no components.')};foreach($c in $comps){if($known -notcontains $c){throw(New-Rejection "Component '$c' is not configured on this server.")}};$expected=@{};foreach($p in $Manifest.files.PSObject.Properties){$rel=$p.Name.Replace('/','\');if(-not(Test-SafeRelativePath $rel)){throw(New-Rejection "Unsafe path in manifest: $($p.Name)")};$top=$rel.Split('\')[0].ToLowerInvariant();if(@('api','web','sql') -notcontains $top){throw(New-Rejection "File outside api/web/sql: $($p.Name)")};$expected[$rel.ToLowerInvariant()]=([string]$p.Value).ToLowerInvariant()};$rootLen=([IO.Path]::GetFullPath($WorkDir).TrimEnd('\')+'\').Length;$seen=@{};foreach($f in Get-ChildItem -LiteralPath $WorkDir -Recurse -File){$rel=$f.FullName.Substring($rootLen);if($rel -ieq 'manifest.json' -or $rel -ieq 'manifest.sig'){continue};$key=$rel.ToLowerInvariant();if(-not $expected.ContainsKey($key)){throw(New-Rejection "File not listed in signed manifest: $rel")};$actual=(Get-FileHash -Algorithm SHA256 -LiteralPath $f.FullName).Hash.ToLowerInvariant();if($actual -ne $expected[$key]){throw(New-Rejection "Hash mismatch: $rel")};$seen[$key]=$true};foreach($k in $expected.Keys){if(-not $seen.ContainsKey($k)){throw(New-Rejection "File listed in manifest but missing: $k")}};foreach($s in @($Manifest.sql|Where-Object{$_})){if($s -notmatch '^sql/[^/\\]+\.sql$'){throw(New-Rejection "Invalid SQL entry: $s")};if(-not $expected.ContainsKey($s.Replace('/','\').ToLowerInvariant())){throw(New-Rejection "SQL file not in package: $s")}};foreach($c in $comps){foreach($d in @($Manifest.delete.$c|Where-Object{$_})){if(-not(Test-SafeRelativePath $d)){throw(New-Rejection "Unsafe delete path: $d")}}} }
function Get-SitePath { param([string]$IisPath);[Environment]::ExpandEnvironmentVariables((Get-Item -Path $IisPath).physicalPath) }
function Get-SitePool { param([string]$IisPath);(Get-Item -Path $IisPath).applicationPool }
function Set-SitePath { param([string]$IisPath,[string]$Path);Set-ItemProperty -Path $IisPath -Name physicalPath -Value $Path }
function Restart-Pool { param([string]$Pool);if((Get-WebAppPoolState -Name $Pool).Value -ne 'Stopped'){Stop-WebAppPool -Name $Pool;$deadline=(Get-Date).AddSeconds(40);while((Get-WebAppPoolState -Name $Pool).Value -ne 'Stopped' -and (Get-Date)-lt $deadline){Start-Sleep -Milliseconds 500}};Start-WebAppPool -Name $Pool }
function Wait-Healthy { param([string]$Url,[int]$TimeoutSec=90);$deadline=(Get-Date).AddSeconds($TimeoutSec);while((Get-Date)-lt $deadline){try{$r=Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 10;if($r.StatusCode -ge 200 -and $r.StatusCode -lt 300){return $true}}catch{};Start-Sleep -Seconds 2};$false }
function Invoke-Robocopy { param([string]$Source,[string]$Destination,[string[]]$Extra=@());$rc=@($Source,$Destination,'/E','/XJ','/NFL','/NDL','/NJH','/NJS','/NP','/R:2','/W:2')+$Extra;& robocopy.exe @rc|Out-Null;if($LASTEXITCODE -ge 8){throw "robocopy failed ($LASTEXITCODE): $Source -> $Destination"};$global:LASTEXITCODE=0 }
function New-Junction { param([string]$Link,[string]$Target);if(-not(Test-Path -LiteralPath $Target)){New-Item -ItemType Directory -Path $Target -Force|Out-Null};if(Test-Path -LiteralPath $Link){Remove-Item -LiteralPath $Link -Recurse -Force};& cmd.exe /c "mklink /J `"$Link`" `"$Target`""|Out-Null;if($LASTEXITCODE -ne 0){throw "mklink /J failed: $Link -> $Target"} }
function Remove-ReleaseDir { param([string]$Dir,[string[]]$SharedDirs);if(-not(Test-Path -LiteralPath $Dir)){return};foreach($d in $SharedDirs){$link=Join-Path $Dir $d;if(Test-Path -LiteralPath $link){$item=Get-Item -LiteralPath $link -Force;if($item.Attributes -band [IO.FileAttributes]::ReparsePoint){& cmd.exe /c "rmdir `"$link`""|Out-Null}}};Remove-Item -LiteralPath $Dir -Recurse -Force -ErrorAction SilentlyContinue }
function New-ReleaseDir { param([string]$Comp,[string]$Version,[string]$Mode,[string]$CurrentDir,[string]$PackageDir,$DeleteList);$c=Get-Component $Comp;$dest=Join-Path $script:Root "releases\$Comp\$Version";if(Test-Path -LiteralPath $dest){throw(New-Rejection "Release $Comp/$Version already exists on the server.")};$shared=@($c.sharedDirs);$skip=@();foreach($d in $shared){$skip+=Join-Path $CurrentDir $d};New-Item -ItemType Directory -Path $dest -Force|Out-Null;if($Mode -eq 'overlay'){$xd=@();if($skip.Count -gt 0){$xd=@('/XD')+$skip};Invoke-Robocopy -Source $CurrentDir -Destination $dest -Extra $xd};if(Test-Path -LiteralPath $PackageDir){Invoke-Robocopy -Source $PackageDir -Destination $dest};foreach($rel in @($DeleteList|Where-Object{$_})){$t=Join-Path $dest $rel;if(Test-Path -LiteralPath $t){Remove-Item -LiteralPath $t -Recurse -Force}};foreach($f in @($script:Cfg.preserveFiles)){$src=Join-Path $CurrentDir $f;if(Test-Path -LiteralPath $src){$target=Join-Path $dest $f;$parent=Split-Path -Parent $target;if(-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};Copy-Item -LiteralPath $src -Destination $target -Force}};foreach($d in $shared){New-Junction -Link (Join-Path $dest $d) -Target (Join-Path $script:Root "shared\$Comp\$d")};$dest }
function Invoke-SqlScript { param([string]$Path);$sql=$script:Cfg.sql;if(-not(Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)){throw 'sqlcmd.exe was not found in PATH.'};$out=& sqlcmd.exe -S $sql.server -d $sql.database -E -I -b -f 65001 -i $Path 2>&1;if($LASTEXITCODE -ne 0){$text=($out|Out-String);if($text.Length -gt 1500){$text=$text.Substring(0,1500)};throw "SQL script failed: $(Split-Path -Leaf $Path)`n$text"} }
function Remove-OldReleases { param([string]$Comp,[string[]]$Protect);$keep=[int]$script:Cfg.keepReleases;$c=Get-Component $Comp;$base=Join-Path $script:Root "releases\$Comp";$dirs=@(Get-ChildItem -LiteralPath $base -Directory|Sort-Object CreationTime -Descending);$i=0;foreach($d in $dirs){$i++;if($i -le $keep){continue};if($Protect -contains $d.FullName.TrimEnd('\')){continue};Write-UpdLog "Removing old release $($d.FullName)";Remove-ReleaseDir -Dir $d.FullName -SharedDirs @($c.sharedDirs)} }
