namespace FVN_REGISTER.Contract.Dtos.EquipmentImport;
public sealed class ExcelSchemaFieldDto{public string FieldKey{get;set;}=string.Empty;public string FieldLabel{get;set;}=string.Empty;public string DataType{get;set;}="Text";public bool IsRequired{get;set;}public bool AllowEmpty{get;set;}=true;public int SourceColumnIndex{get;set;}public string? HeaderName{get;set;}public string? ResourceKey{get;set;}public string? TargetProperty{get;set;}public string? Format{get;set;}public string? ValidationRule{get;set;}public string? DefaultValue{get;set;}public int? MaxLength{get;set;}public int DisplayOrder{get;set;}}
public sealed class SaveExcelSchemaFieldRequest{public int SchemaId{get;set;}public string FieldKey{get;set;}=string.Empty;public string FieldLabel{get;set;}=string.Empty;public string DataType{get;set;}="Text";public bool IsRequired{get;set;}public bool AllowEmpty{get;set;}=true;public int SourceColumnIndex{get;set;}public string? HeaderName{get;set;}public string? ResourceKey{get;set;}public string? TargetProperty{get;set;}public string? Format{get;set;}public string? ValidationRule{get;set;}public string? DefaultValue{get;set;}public int? MaxLength{get;set;}public int DisplayOrder{get;set;}}
public sealed class ExcelSchemaDto{public int Id{get;set;}public string ModuleCode{get;set;}="EQUIPMENT";public string EntityCode{get;set;}="EQUIPMENT_ASSET";public string SchemaCode{get;set;}=string.Empty;public string SchemaName{get;set;}=string.Empty;public int Version{get;set;}public string Status{get;set;}="Draft";public bool IsActive{get;set;}public int DepartmentCode { get; set; }public int CreatedByUserId{get;set;}public string CreatedByUserName{get;set;}=string.Empty;public string? SourceFileName{get;set;}public int? SourceSchemaId{get;set;}public bool CreatedFromExcel{get;set;}public bool IsOwner{get;set;}public bool CanEdit{get;set;}public bool CanCreateVersion{get;set;}public bool CanClone{get;set;}public int SheetIndex{get;set;}public string SheetName{get;set;}=string.Empty;public int HeaderRowIndex{get;set;}public int DataStartRowIndex{get;set;}public int? DataEndRowIndex{get;set;}public List<ExcelSchemaFieldDto> Fields{get;set;}=new();}
public sealed class ExcelSchemaUpsertRequest{public int? Id{get;set;}public string ModuleCode{get;set;}="EQUIPMENT";public string EntityCode{get;set;}="EQUIPMENT_ASSET";public int DepartmentCode { get; set; }public string SchemaName{get;set;}=string.Empty;public string Status{get;set;}="Draft";}
public sealed class ExcelSchemaCloneRequest{public string? SchemaName{get;set;}}
public sealed class ExcelSchemaSummaryDto{public int Id{get;set;}public string ModuleCode{get;set;}="EQUIPMENT";public string EntityCode{get;set;}="EQUIPMENT_ASSET";public string SchemaCode{get;set;}=string.Empty;public string SchemaName{get;set;}=string.Empty;public int DepartmentCode { get; set; }public int Version{get;set;}public string Status{get;set;}="Draft";public bool IsActive{get;set;}public int FieldCount{get;set;}public int CreatedByUserId{get;set;}public string CreatedByUserName{get;set;}=string.Empty;public DateTime CreatedAt{get;set;}public DateTime? UpdatedAt{get;set;}public string? SourceFileName{get;set;}public bool CreatedFromExcel{get;set;}public bool IsOwner{get;set;}public bool CanEdit{get;set;}public bool CanCreateVersion{get;set;}public bool CanClone{get;set;}}
public sealed class ExcelSchemaFromExcelDto{public string FileName{get;set;}=string.Empty;public string SheetName{get;set;}=string.Empty;public string SuggestedSchemaName{get;set;}=string.Empty;public int ColumnCount{get;set;}public int SampleRowCount{get;set;}public List<ExcelSchemaFieldDto> Fields{get;set;}=new();}
public sealed class ExcelWorkbookDto{public string FileName{get;set;}=string.Empty;public List<ExcelSheetDto> Sheets{get;set;}=new();}
public sealed class ExcelSheetDto{public int Index{get;set;}public string Name{get;set;}=string.Empty;public int RowCount{get;set;}public int ColumnCount{get;set;}public bool HasData{get;set;}}
public sealed class ExcelGridRowDto{public int RowIndex{get;set;}public bool IsGroupedOrHidden{get;set;}public List<string?> Cells{get;set;}=new();}
public sealed class ExcelGridDto{public string FileName{get;set;}=string.Empty;public int SheetIndex{get;set;}public int TotalRowCount{get;set;}public int ColumnCount{get;set;}public List<ExcelGridRowDto> Rows{get;set;}=new();}
public sealed class ExcelRangeRequest{public int SheetIndex{get;set;}public int HeaderRowIndex{get;set;}public List<int>? SelectedColumnIndexes{get;set;}public int? DataStartRowIndex{get;set;}public int? DataEndRowIndex{get;set;}}
public sealed class ExcelImportBatchDto{public long Id{get;set;}public int SchemaId{get;set;}public string ModuleCode{get;set;}="EQUIPMENT";public string EntityCode{get;set;}="EQUIPMENT_ASSET";public string FileName{get;set;}=string.Empty;public string Status{get;set;}=string.Empty;public int TotalRows{get;set;}public int ValidRows{get;set;}public int InvalidRows{get;set;}public int ImportedRows{get;set;}public List<ExcelImportRowDto> Rows{get;set;}=new();}
public sealed class ExcelImportRowDto{public long Id{get;set;}public int RowNumber{get;set;}public string Status{get;set;}=string.Empty;public string? ErrorMessage{get;set;}}
public sealed class ExcelImportCommitResultDto{public long BatchId{get;set;}public int ImportedRows{get;set;}public int SkippedRows{get;set;}}