using FVN_REGISTER.Contract.Dtos.Depts;
using FVN_REGISTER.Contract.Dtos.Equipment;
using FVN_REGISTER.Contract.Dtos.EquipmentForms;
using FVN_REGISTER.Contract.Dtos.EquipmentImport;
using FVN_REGISTER.Contract.Dtos.PublicForms;
using FVN_REGISTER.Contract.Responses;
using Microsoft.AspNetCore.Components.Forms;

namespace FVN_REGISTER.Shared.Services.Equipment;

public interface IEquipmentClientService
{
    Task<ApiResponse<List<DepartmentDto>>> GetEquipmentDepartmentsAsync(CancellationToken ct = default);
    Task<ApiResponse<EquipmentActionAccessDto>> GetActionsAsync(CancellationToken ct = default);
    Task<ApiResponse<bool>> HasAccessAsync(CancellationToken ct = default);
    Task<ApiResponse<bool>> HasImportAccessAsync(CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentHandoverEmployeeOptionDto>>> GetAssignmentEmployeesAsync(string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentApproverDto>>> GetApproversAsync(string deptCode, CancellationToken ct = default);
    Task<ApiResponse<EquipmentRequestDto>> CreateRegistrationAsync(CreateEquipmentRegistrationDto request, CancellationToken ct = default);
    Task<ApiResponse<EquipmentRequestDto>> SubmitRegistrationAsync(int id, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentRequestDto>>> GetMineAsync(CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentAssetDto>>> GetMyAssignedAssetsAsync(CancellationToken ct = default);
    Task<ApiResponse<EquipmentRequestDto>> CreateRepairAsync(CreateEquipmentRepairDto request, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentHandoverEmployeeOptionDto>>> GetRepairAssigneesAsync(string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<EquipmentRequestDto>> SubmitRepairAsync(int id, CancellationToken ct = default);
    Task<ApiResponse<EquipmentRequestDto>> CompleteRepairAsync(int id, string feedback, CancellationToken ct = default);
    Task<ApiResponse<EquipmentAssetDto>> ScanAsync(string token, CancellationToken ct = default);
    Task<ApiResponse<EquipmentAssetDto>> GetAssetAsync(int id, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentHandoverEmployeeOptionDto>>> GetHandoverEmployeesAsync(string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentHandoverCandidateDto>>> GetHandoverCandidatesAsync(string oldEmployeeCode, string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<EquipmentHandoverResultDto>> HandoverAsync(EquipmentHandoverRequest request, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentReportRowDto>>> GetReportAsync(EquipmentReportFilterDto filter, CancellationToken ct = default);
    Task<ApiResponse<byte[]>> ExportReportAsync(EquipmentReportFilterDto filter, CancellationToken ct = default);
    Task<ApiResponse<List<ExcelSchemaSummaryDto>>> GetSchemasAsync(string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaDto>> GetSchemaAsync(int schemaId, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaDto>> SaveSchemaAsync(ExcelSchemaUpsertRequest request, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaDto>> CloneSchemaAsync(int schemaId, ExcelSchemaCloneRequest request, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaDto>> CreateSchemaVersionAsync(int schemaId, CancellationToken ct = default);
    Task<ApiResponse<bool>> DeleteSchemaAsync(int schemaId, CancellationToken ct = default);
    Task<ApiResponse<ExcelWorkbookDto>> InspectExcelAsync(string deptCode, IBrowserFile file, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaFromExcelDto>> PreviewSchemaFromExcelAsync(string deptCode, IBrowserFile file, int sheetIndex = 0, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaFromExcelDto>> PreviewSchemaFromExcelAsync(string deptCode, IBrowserFile file, CancellationToken ct);
    Task<ApiResponse<ExcelSchemaDto>> CreateSchemaFromExcelAsync(string deptCode, IBrowserFile file, string? schemaName = null, int sheetIndex = 0, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaDto>> CreateSchemaFromExcelAsync(string deptCode, IBrowserFile file, string? schemaName, CancellationToken ct);
    Task<ApiResponse<ExcelGridDto>> GetExcelGridAsync(string deptCode, IBrowserFile file, int sheetIndex, int maxRows = 200, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaFromExcelDto>> PreviewSchemaFromExcelRangeAsync(string deptCode, IBrowserFile file, ExcelRangeRequest range, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaDto>> CreateSchemaFromExcelRangeAsync(string deptCode, IBrowserFile file, ExcelRangeRequest range, string? schemaName = null, CancellationToken ct = default);
    Task<ApiResponse<ExcelSchemaFieldDto>> SaveSchemaFieldAsync(SaveExcelSchemaFieldRequest request, CancellationToken ct = default);
    Task<ApiResponse<ExcelImportBatchDto>> StageImportAsync(string deptCode, int? schemaId, IBrowserFile file, bool assignToEmployee = false, int sheetIndex = 0, CancellationToken ct = default);
    Task<ApiResponse<ExcelImportBatchDto>> StageImportAsync(string deptCode, int? schemaId, IBrowserFile file, bool assignToEmployee, CancellationToken ct);
    Task<ApiResponse<ExcelImportCommitResultDto>> CommitImportAsync(long batchId, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentAssetDto>>> GetRegisteredInspectionAssetsAsync(string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentInspectionTemplateDto>>> GetInspectionTemplatesAsync(string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTemplateDto>> GetInspectionTemplateAsync(int id, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTemplateImportResultDto>> ImportInspectionTemplateExcelAsync(IBrowserFile file, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTemplateDto>> SaveInspectionTemplateAsync(EquipmentInspectionTemplateUpsertRequest request, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTemplateDto>> CloneInspectionTemplateAsync(int id, string? name = null, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentInspectionAssignmentDto>>> GetInspectionAssignmentsAsync(int? equipmentId = null, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionAssignmentDto>> AssignInspectionAsync(EquipmentInspectionAssignmentRequest request, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentInspectionTaskDto>>> GetInspectionTasksAsync(bool includeCompleted = false, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTaskDto>> GetInspectionTaskAsync(int id, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTaskDto>> SubmitInspectionAsync(EquipmentInspectionSubmitRequest request, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTaskDto>> ApproveInspectionAsync(int id, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionTaskDto>> RejectInspectionAsync(int id, string reason, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionDashboardDto>> GetInspectionDashboardAsync(DateTime from, DateTime to, string? deptCode = null, CancellationToken ct = default);
    Task<ApiResponse<EquipmentInspectionEvidenceDto>> UploadInspectionEvidenceAsync(int taskId, int itemId, IBrowserFile file, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentApplicableFormDto>>> GetApplicableFormsAsync(int assetId, CancellationToken ct = default);
    Task<ApiResponse<List<EquipmentFormAssignmentDto>>> GetEquipmentFormAssignmentsAsync(string equipmentSchemaKey, CancellationToken ct = default);
    Task<ApiResponse<List<PublicFormDto>>> GetEquipmentFormCatalogAsync(CancellationToken ct = default);
    Task<ApiResponse<EquipmentFormAssignmentDto>> AssignEquipmentFormAsync(EquipmentFormAssignmentRequest request, CancellationToken ct = default);
    Task<ApiResponse<bool>> RemoveEquipmentFormAssignmentAsync(int assignmentId, CancellationToken ct = default);
    Task<ApiResponse<EquipmentFormSubmissionDto>> SubmitEquipmentFormAsync(EquipmentFormSubmissionRequest request, CancellationToken ct = default);
}
